#!/usr/bin/guile
!#

(use-modules (sph) (sph cli)
  (sph hashtable) (sph lang sc-format)
  (ice-9 match) (sph lang scheme) (sph alist) (sph tree) (sph list) (srfi srfi-1))

(define cli
  (cli-create #:options
    (q
      ( (format #:value-required? #t
          #:description
          "custom configuration for expression distribution. example: \"1,1,1:myprefix1,myprefix2;2,1,1:myprefix3\"")))))

(define (parse-format a)
  (map
    (l (a)
      (apply (l (counts prefixes) (list (map string->number counts) (map string->symbol prefixes)))
        (map (l (a) (string-split a #\,)) (string-split a #\:))))
    (string-split a #\;)))

#;(define merge-and-simplify-test-daat
  (define (test a) (declare a b c d)
    (declare e f g h) (declare i j)
    (set a 1) (set c (struct-get v z))
    (declare k) (set d (address-of x))
    (declare l) (declare m)
    (set e (pointer-get (+ a 3))) (set (struct-pointer-get f u t) (address-of (pointer-get y)))
    (define a b 3) (define c d 4)))

(define (merge-and-simplify a)
  (tree-map-lists-self
    (l (a)
      (let
        (a
          (fold
            (l (p a)
              (map-consecutive (l (b) (and (list? b) (not (null? b)) (p b)))
                (l b (append (first b) (apply append (map (l (b) (tail b)) (tail b))))) a))
            a
            (pair (l (a) (match a (((quote define) (? symbol?) value _ ...) #t) (_ #f)))
              (map (l (prefix) (l (a) (eq? prefix (first a))))
                (quote (declare set set+ set- pre-define))))))
        (match a (((quote pointer-get) (? symbol? b)) (symbol-append (q *) b))
          (((quote address-of) (? symbol? b)) (symbol-append (q &) b))
          ( ( (quote struct-get) (? symbol? b) ...)
            (string->symbol (string-join (map symbol->string b) ".")))
          ( ( (quote struct-pointer-get) (? symbol? b) ...)
            (string->symbol (string-join (map symbol->string b) ":")))
          (_ a))))
    a))

(define (sc-format-cli)
  (let* ((options (cli)) (format (alist-ref options (q format))))
    (if format
      (each
        (l (a)
          (apply
            (l (counts prefixes)
              (each (l (prefix) (ht-set! sc-formatters prefix (apply sc-f counts))) prefixes))
            a))
        (parse-format format)))
    (display (sc-format (merge-and-simplify (port->datums (current-input-port) read))))))

(sc-format-cli)
