#!/usr/bin/guile
!#

(use-modules (ice-9 match) (srfi srfi-1)
  (sph lang sc sph) (sph lang sc sph cli)
  (sph lang sc sph hashtable) (sph lang sc-format)
  (sph lang sc sph lang scheme) (sph lang sc sph alist) (sph lang sc sph tree) (sph lang sc sph list))

(define cli
  (cli-create #:options
    (q
      ( (format #:value-required? #t
          #:description
          "custom configuration for expression distribution. example: \"1,1,1:myprefix1,myprefix2;2,1,1:myprefix3\"")))))

(define (parse-format a)
  (map
    (l (a)
      (apply (l (counts prefixes) (list (map string->number counts) (map string->symbol prefixes)))
        (map (l (a) (string-split a #\,)) (string-split a #\:))))
    (string-split a #\;)))

(define (merge-simplify a)
  (if (and (not (null? a)) (contains? (quote (define begin while for)) (first a)))
    (fold
      (l (p a)
        (map-consecutive (l (b) (and (list? b) (not (null? b)) (p b)))
          (l b (append (first b) (apply append (map (l (b) (tail b)) (tail b))))) a))
      a
      (pair (l (a) (match a (((quote define) (? symbol?) value _ ...) #t) (_ #f)))
        (map (l (prefix) (l (a) (eq? prefix (first a)))) (quote (declare set set+ set- pre-define)))))
    a))

"(struct-pointer-get (struct-pointer-get a b) c)\n(address-of (array-get a b))\n(pointer-get (+ a b))\n(pointer-get (+ a b c))\n(struct-pointer-get (+ a b) c)"

(define (replace-simplify a)
  (match a (((quote pointer-get) (? symbol? b)) (symbol-append (q *) b))
    (((quote address-of) (? symbol? b)) (symbol-append (q &) b))
    ( ( (quote struct-get) (? symbol? b) ...)
      (string->symbol (string-join (map symbol->string b) ".")))
    ( ( (quote struct-pointer-get) (? symbol? b) ...)
      (string->symbol (string-join (map symbol->string b) ":")))
    (((quote begin) b) b)
    ( ( (quote define) (name formals ...) (type) body ...)
      (pairs (q define) (pair name formals) type body))
    ( ( (quote struct-pointer-get) ((quote struct-pointer-get) a b) c)
      (list (q struct-pointer-get) a b c))
    (((quote struct-get) ((quote struct-get) a b) c) (list (q struct-get) a b c))
    (((quote address-of) ((quote array-get) a b)) (list (q +) a b))
    (((quote pointer-get) ((quote +) a b)) (list (q array-get) a b))
    (((quote pointer-get) ((quote +) a b ...)) (list (q array-get) a (pair (q +) b)))
    ( ( (quote struct-pointer-get) ((quote +) a b) c ...)
      (pairs (q struct-get) (list (q array-get) a b) c))
    (_ a)))

(define (merge-and-simplify a)
  "currently not used because it merges subsequent set in if, for, and custom macros"
  (tree-map-lists-self (l (a) (replace-simplify (merge-simplify a))) a))

(define (sc-format-cli)
  (let* ((options (cli)) (format (alist-ref options (q format))))
    (if format
      (each
        (l (a)
          (apply
            (l (counts prefixes)
              (each (l (prefix) (ht-set! sc-formatters prefix (apply sc-f counts))) prefixes))
            a))
        (parse-format format)))
    (display (sc-format (merge-and-simplify (port->datums (current-input-port) read))))))

(sc-format-cli)
