#!/usr/bin/guile
!#

(use-modules (sph) (sph cli) (sph lang sc-format) (sph lang scheme))
(define cli (cli-create))

(define (sc-format-cli)
  (let (options (cli))
    (display (sc-format (port->datums (current-input-port) read)))))

(sc-format-cli)
